### ISSUE TITLE
Is it only for no_std?

### ISSUE THREAD

**Issue by vi** [japaric/panic-never#2]
If yes, this should be documented.

Otherwise it seems to just fail. I only `cargo add`ed, it does nothing. If I also add it as `extern crate panic_never`, I get linker error regardless of panic:

```
   Compiling panic-never-test v0.1.0 (/tmp/panic-never-test)
error: duplicate lang item in crate `panic_never`: `panic_impl`.
  |
  = note: first defined in crate `std`.

error: aborting due to previous error

error: Could not compile `panic-never-test`.
```

**Comment by japaric** [comment]
> Is it only for no_std?

This is a (current) limitation of the `#[panic_handler]` feature. I have added a note to the documentation.

I should add that even the smallest `std` program: `fn main() {}` contains several panicking branches (because the Rust startup code can fail in unrecoverable ways) so even if you could link `std` programs to `panic-never` linking would always fail.
